/*Este archivo se crea para declarar los personajes como se va a hecer en la base de datos
*Con esto nos aseguramos que vaya a funcionar cuando de consuman los servicios 
*/
var personajesBuenos={
	"idPUno":{"nombre":"Ana Pantera","rutaSprite":"../img/personajes/personajesBuenos/pantera.png",
			  "rutaAvatar":"../img/personajes/avatares/caraPantera.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderPantera.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/Ana Pantera.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoGallo.png",
			  "daño":[6,10],"energia":0.2,"defensa":10,"vida":200,"nivel":3},

	"idPDos":{"nombre":"Andrés Gallo","rutaSprite":"../img/personajes/personajesBuenos/gallo.png",
			  "rutaAvatar":"../img/personajes/avatares/caraGallo.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderGallo.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/AndresGallo.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoLeon.png",
			  "daño":[6,10],"energia":1,"defensa":10,"vida":200,"nivel":4},
    
    "idPTres":{"nombre":"Cata Cierva","rutaSprite":"../img/personajes/personajesBuenos/cierva.png",
			  "rutaAvatar":"../img/personajes/avatares/caraCierva.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderCierva.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/Cata Cierva.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoGallo.png",
			  "daño":[6,10],"energia":1,"defensa":10,"vida":200,"nivel":5},

	"idPCuatro":{"nombre":"Daniela Jirafa","rutaSprite":"../img/personajes/personajesBuenos/jirafa.png",
			  "rutaAvatar":"../img/personajes/avatares/caraJirafa.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderJirafa.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/Daniela Jirafa.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoLeon.png",
			  "daño":[6,10],"energia":1,"defensa":10,"vida":200,"nivel":6},
    
    "idPCinco":{"nombre":"Daniel León","rutaSprite":"../img/personajes/personajesBuenos/leon.png",
			  "rutaAvatar":"../img/personajes/avatares/caraLeon.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderLeon.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/DanielLeon.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoGallo.png",
			  "daño":[6,10],"energia":1,"defensa":10,"vida":200,"nivel":7},

	"idPSeis":{"nombre":"Fabián Canario","rutaSprite":"../img/personajes/personajesBuenos/canario.png",
			  "rutaAvatar":"../img/personajes/avatares/caraCanario.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderCanario.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/Fabian Canario.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoLeon.png",
			  "daño":[6,10],"energia":1,"defensa":10,"vida":200,"nivel":8},
    
    "idPSiete":{"nombre":"Iván Ruiseñor","rutaSprite":"../img/personajes/personajesBuenos/ruisenor.png",
			  "rutaAvatar":"../img/personajes/avatares/caraRuiseñor.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderRuisenor.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/Ivan Ruisenor.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoGallo.png",
			  "daño":[6,10],"energia":1,"defensa":10,"vida":200,"nivel":3},

	"idPOcho":{"nombre":"Pedro Ratón","rutaSprite":"../img/personajes/personajesBuenos/raton.png",
			  "rutaAvatar":"../img/personajes/avatares/caraRatón.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderRaton.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/Pedro Raton.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoLeon.png",
              "daño":[6,10],"energia":1,"defensa":10,"vida":200,"nivel":3},
              
    "idPNueve":{"nombre":"Tati Hormiga","rutaSprite":"../img/personajes/personajesBuenos/hormiga.png",
			  "rutaAvatar":"../img/personajes/avatares/caraHormiga.png",
              "rutaBotonPoder":"../img/personajes/poderes/PoderesBotones/botonPoderHormiga.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadBuenos/tati Hormiga.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoGallo.png",
			  "daño":[6,10],"energia":1,"defensa":10,"vida":200,"nivel":2}
}

var personajesMalos={
    /*Enemigos ZORROS MUNDO 1 ***********************************************************************************************/
    
    "idPUno":{"nombre":"Arthur El Veloz","rutaSprite":"../img/personajes/miniPersonajes/Zorro/ZorroVeloz.png",
			  "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/ArthurVeloz.png",
			  "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			  "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			  "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPDos":{"nombre":"Andy El Gris","rutaSprite":"../img/personajes/miniPersonajes/Zorro/ZorroGris.png",
			  "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/AndyGris.png",
			  "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			  "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			  "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTres":{"nombre":"Ander El Ártico","rutaSprite":"../img/personajes/miniPersonajes/Zorro/ZorroArtico.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/AnderArtico.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCuatro":{"nombre":"Arnold El Desierto","rutaSprite":"../img/personajes/miniPersonajes/Zorro/ZorroDesierto.png",
                 "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			     "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/ArnoldDesierto.png",
			     "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			     "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			     "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			     "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCinco":{"nombre":"Andrés Zorro","rutaSprite":"../img/personajes/personajesMalos/zorro.png",
                "rutaAvatar":"../img/personajes/avatares/caraZorro.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/FabianBabuino  PERSONALIDAD.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos OSOS MUNDO 2 ************************************************************************************************/
    
    "idPSeis":{"nombre":"Pepe Pardo","rutaSprite":"../img/personajes/miniPersonajes/Oso/OsoPardo.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/PepePardo.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPSiete":{"nombre":"Enrique Malayo","rutaSprite":"../img/personajes/miniPersonajes/Oso/OsoMalayo.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
                "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/EnriqueMalayo.png",
                "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
                "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
                "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
                "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPOcho":{"nombre":"Leonardo Polar","rutaSprite":"../img/personajes/miniPersonajes/Oso/OsoPolar.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/LeonardoPolar.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPNueve":{"nombre":"Luke Grizzly","rutaSprite":"../img/personajes/miniPersonajes/Oso/OsoGrizzly.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/LukeGrizzly.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPDiez":{"nombre":"Felipe Oso","rutaSprite":"../img/personajes/personajesMalos/oso.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/camiloPERSONALIDAD.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos PEREZOSOS MUNDO 3 ***********************************************************************************************/
    
    "idPOnce":{"nombre":"Jamal 3 dedos","rutaSprite":"../img/personajes/miniPersonajes/Perezoso/PerezosoJamal.png",
			  "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/Jamal3Dedos.png",
			  "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			  "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			  "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPDoce":{"nombre":"William 2 dedos","rutaSprite":"../img/personajes/miniPersonajes/Perezoso/PerezosoWilliam.png",
			  "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/William2Dedos.png",
			  "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			  "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			  "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTrece":{"nombre":"René Piramil","rutaSprite":"../img/personajes/miniPersonajes/Perezoso/PerezosoRene.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/RenePiramil.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCatorce":{"nombre":"Asher Dúo-Piramil","rutaSprite":"../img/personajes/miniPersonajes/Perezoso/PerezosoAsher.png",
                 "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			     "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/AsherPiramil.png",
			     "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			     "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			     "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			     "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPQuince":{"nombre":"Camilo Perezoso","rutaSprite":"../img/personajes/personajesMalos/perezoso.png",
                "rutaAvatar":"../img/personajes/avatares/caraPerezoso.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/CamiloPERSONALIDAD.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos BURROS MUNDO 4 ***********************************************************************************************/
    
    "idPDieciseis":{"nombre":"Christian Mamut","rutaSprite":"../img/personajes/miniPersonajes/Burro/BurroMamut.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/ChristianMamut.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPDiecisiete":{"nombre":"Javier Zamorano","rutaSprite":"../img/personajes/miniPersonajes/Burro/BurroZamorano.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
                "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/JavierZamorano.png",
                "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
                "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
                "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
                "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPDieciocho":{"nombre":"Marco Andaluz","rutaSprite":"../img/personajes/miniPersonajes/Burro/BurroAndaluz.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/MarcoAndaluz.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPDiecinueve":{"nombre":"Franklin Provence","rutaSprite":"../img/personajes/miniPersonajes/Burro/BurroProvence.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/FranklinProvence.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPVeinte":{"nombre":"Julián Burro","rutaSprite":"../img/personajes/personajesMalos/Burro.png",
               "rutaAvatar":"../img/personajes/avatares/caraBurro.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/JulianPERSONALIDAD.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos CAMALEONES MUNDO 5 ***********************************************************************************************/
    
    "idPVeintiuno":{"nombre":"Tobby Pantera","rutaSprite":"../img/personajes/miniPersonajes/Camaleon/CamaleonPantera.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/TobbyPantera.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPVeintidos":{"nombre":"Uriel Tigre","rutaSprite":"../img/personajes/miniPersonajes/Camaleon/CamaleonTigre.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
                "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/UrielTigre.png",
                "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
                "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
                "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
                "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPVeintitres":{"nombre":"Izaro Pigmeo","rutaSprite":"../img/personajes/miniPersonajes/Camaleon/CamaleonPigmeo.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/IzaroPigmeos.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPVeinticuatro":{"nombre":"Samay Rieppeleon","rutaSprite":"../img/personajes/miniPersonajes/Camaleon/CamaleonRieppeleon.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/SamayRieppeleon.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPVeinticinco":{"nombre":"Juan Camaleón","rutaSprite":"../img/personajes/personajesMalos/camaleon.png",
               "rutaAvatar":"../img/personajes/avatares/caraCamaleon.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/Juan Camaleon PERSONALIDAD.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos ABEJAS MUNDO 6 ***********************************************************************************************/
    
    "idPVeintiseis":{"nombre":"Marlene Abejorro","rutaSprite":"../img/personajes/miniPersonajes/Abeja/AbejaAbejorro.png",
			  "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/MarleneAbejorro.png",
			  "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			  "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			  "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPVeintisiete":{"nombre":"Gloria Africanizada","rutaSprite":"../img/personajes/miniPersonajes/Abeja/AbejaAfricanizada.png",
			  "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/GloriaAfricanizada.png",
			  "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			  "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			  "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPVeintiocho":{"nombre":"Evelyn Parasito","rutaSprite":"../img/personajes/miniPersonajes/Abeja/AbejaParasito.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/EvelynParasitas.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPVeintinueve":{"nombre":"Camila Nocturna","rutaSprite":"../img/personajes/miniPersonajes/Abeja/AbejaNocturna.png",
                 "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			     "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/CamilaNocturna.png",
			     "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			     "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			     "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			     "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTreinta":{"nombre":"Ana Abeja","rutaSprite":"../img/personajes/personajesMalos/abeja1.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/Ana Sara PERSONALIDAD.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTreintax":{"nombre":"Sara Abeja","rutaSprite":"../img/personajes/personajesMalos/abeja2.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/Ana Sara PERSONALIDAD.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos RATAS MUNDO 7 ***********************************************************************************************/
    
    "idPTreintayuno":{"nombre":"Mario Mus","rutaSprite":"../img/personajes/miniPersonajes/Rata/RataMus.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/MarioMus.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPTreintaydos":{"nombre":"Jasón Gris","rutaSprite":"../img/personajes/miniPersonajes/Rata/RataGris.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
                "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/JasonFris.png",
                "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
                "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
                "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
                "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTreintaytres":{"nombre":"Everth Negro","rutaSprite":"../img/personajes/miniPersonajes/Rata/RataNegra.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/EverthNegro.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTreintaycuatro":{"nombre":"Hilario Rattus","rutaSprite":"../img/personajes/miniPersonajes/Rata/RataRattus.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/HilarioRattus.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTreintaycinco":{"nombre":"Juan Rata","rutaSprite":"../img/personajes/personajesMalos/rata.png",
               "rutaAvatar":"../img/personajes/avatares/caraRata.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/Juan Rata PERSONALIDAD.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos BUITRES MUNDO 8 ***********************************************************************************************/
    
    "idPTreintayseis":{"nombre":"Ezequiel Alimoche","rutaSprite":"../img/personajes/miniPersonajes/Buitre/BuitreAlimoche.png",
			  "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/EzequielAlimoche.png",
			  "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			  "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			  "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPTreintaysiete":{"nombre":"Alexis Cuervo","rutaSprite":"../img/personajes/miniPersonajes/Buitre/BuitreCuervo.png",
			  "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			  "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/AlexisCuervo.png",
			  "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			  "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			  "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			  "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTreintayocho":{"nombre":"César Negro","rutaSprite":"../img/personajes/miniPersonajes/Buitre/BuitreNegro.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/CesarBuitreNegro.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPTreintaynueve":{"nombre":"Antonio Cornejo","rutaSprite":"../img/personajes/miniPersonajes/Buitre/BuitreCorneja.png",
                 "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			     "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/AntonioCornejo.png",
			     "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			     "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			     "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			     "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCuarenta":{"nombre":"Carlos Buitre","rutaSprite":"../img/personajes/personajesMalos/buitre.png",
                "rutaAvatar":"../img/personajes/avatares/caraBuitre.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/Carlos PERSONALIDAD.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos HIENAS MUNDO 9 ***********************************************************************************************/
    
    "idPCuarentayuno":{"nombre":"Tracy Rayada","rutaSprite":"../img/personajes/miniPersonajes/Hiena/HienaRayada.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/TracyRayada.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPCuarentaydos":{"nombre":"Petro Parda","rutaSprite":"../img/personajes/miniPersonajes/Hiena/HienaParda.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
                "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/PetroParda.png",
                "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
                "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
                "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
                "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCuarentaytres":{"nombre":"Trevor Manchada","rutaSprite":"../img/personajes/miniPersonajes/Hiena/HienaManchada.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/TrevorManchada.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCuarentaycuatro":{"nombre":"Jaime Próteles","rutaSprite":"../img/personajes/miniPersonajes/Hiena/HienaProteles.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/JaimeProteles.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCuarentaycinco":{"nombre":"Víctor Hiena","rutaSprite":"../img/personajes/personajesMalos/hiena.png",
               "rutaAvatar":"../img/personajes/avatares/caraHiena.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/VIctor PERSONALIDAD.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos LAGARTOS MUNDO 10 ***********************************************************************************************/
    
    "idPCuarentayseis":{"nombre":"Roberto Camaleón","rutaSprite":"../img/personajes/miniPersonajes/Lagarto/LagartoCamaleon.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/RobertoCamaleon.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPCuarentaysiete":{"nombre":"Fabio Iguana","rutaSprite":"../img/personajes/miniPersonajes/Lagarto/LagartoIguana.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
                "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/FabioIguana.png",
                "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
                "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
                "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
                "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCuarentayocho":{"nombre":"Fito Komodo","rutaSprite":"../img/personajes/miniPersonajes/Lagarto/LagartoKomodo.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/FitoKomodo.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCuarentaynueve":{"nombre":"Andrés Espinoso","rutaSprite":"../img/personajes/miniPersonajes/Lagarto/LagartoEspinoso.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/AndresEspinoso.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCincuenta":{"nombre":"Nicolás Lagarto","rutaSprite":"../img/personajes/personajesMalos/lagarto.png",
               "rutaAvatar":"../img/personajes/avatares/caraLagarto.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/LagartoPERSONALIDAD.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos VIBORAS MUNDO 11 ***********************************************************************************************/
    
    "idPCincuentayuno":{"nombre":"Pedro Aspis","rutaSprite":"../img/personajes/miniPersonajes/Vibora/ViboraAspis.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/PedroAspis.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPCincuentaydos":{"nombre":"Humberto Gaditana","rutaSprite":"../img/personajes/miniPersonajes/Vibora/ViboraGaditana.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
                "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/HumbertoGaditana.png",
                "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
                "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
                "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
                "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCincuentaytres":{"nombre":"Lucas Mamba","rutaSprite":"../img/personajes/miniPersonajes/Vibora/ViboraMamba.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/LucasMamba.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCincuentaycuatro":{"nombre":"Farid Pitón","rutaSprite":"../img/personajes/miniPersonajes/Vibora/ViboraPiton.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/FaridPiton.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCincuentaycinco":{"nombre":"Luis Víbora","rutaSprite":"../img/personajes/personajesMalos/vibora.png",
               "rutaAvatar":"../img/personajes/avatares/caraVibora.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/LuisPERSONALIDAD.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    /*Enemigos BABUINOS MUNDO 12 ***********************************************************************************************/
    
    "idPCincuentayseis":{"nombre":"Peter Mandril","rutaSprite":"../img/personajes/miniPersonajes/Babuino/BabuinoMandril.png",
               "rutaAvatar":"../img/personajes/avatares/caraOso.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/PeterMandril.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},

	"idPCincuentaysiete":{"nombre":"Luis Gibón","rutaSprite":"../img/personajes/miniPersonajes/Babuino/BabuinoGibon.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
                "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/LuisGibon.png",
                "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
                "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
                "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
                "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCincuentayocho":{"nombre":"José Titi Pigmeo","rutaSprite":"../img/personajes/miniPersonajes/Babuino/BabuinoPigmeo.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/JosePigmeo.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPCincuentaynueve":{"nombre":"Macaco Reshus","rutaSprite":"../img/personajes/miniPersonajes/Babuino/BabuinoMacaco.png",
                "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			    "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/miniPersonajes/MacacoReshus.png",
			    "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			    "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			    "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			    "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200},
    
    "idPSesenta":{"nombre":"Fabian Babuino","rutaSprite":"../img/personajes/personajesMalos/babuino.png",
               "rutaAvatar":"../img/personajes/avatares/caraBabuino.png",
			   "rutaAtaque":"../img/personajes/poderes/PoderesPersonalidadMalos/FabianBabuino  PERSONALIDAD.png",
			   "rutaAtaquePlagio":"../img/personajes/poderes/poderesPlagioMalos/error404.png",
			   "rutaImpactoPersonalidad":"../img/personajes/poderes/PoderesImpactos/impactoOso1.png",
			   "rutaImpactoPlagio":"../img/personajes/poderes/PoderesImpactos/impactoOso2.png",
			   "daño":[6,10,15],"energia":[0.5,1],"defensa":10,"vida":200}
}